apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users":[
        {
          "name":"{{ .Values.rabbitmq.auth.username }}",
          "password":"{{ .Files.Get .Values.global.rabbitmq.env | b64dec }}",
          "tags":"administrator"
        }
      ],
      "vhosts":[
        {
          "name":"/"
        }
      ],
      "permissions":[
        {
          "user":"user",
          "vhost":"/",
          "configure":".*",
          "write":".*",
          "read":".*"
        }
      ],
      "queues": [
        {
          "name": "channel_service",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {
            "x-queue-type": "classic"
          }
        },
        {
          "name": "guild_service",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {
            "x-queue-type": "classic"
          }
        },
        {
          "name": "user_service",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {
            "x-queue-type": "classic"
          }
        }
      ],
      "exchanges": [
        {
          "name": "main",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {
          }
        }
      ],
      "bindings": [
        {
          "source": "main",
          "vhost": "/",
          "destination": "channel_service",
          "destination_type": "queue",
          "routing_key": "",
          "arguments": {
          }
        },
        {
          "source": "main",
          "vhost": "/",
          "destination": "guild_service",
          "destination_type": "queue",
          "routing_key": "",
          "arguments": {
          }
        },
        {
          "source": "main",
          "vhost": "/",
          "destination": "user_service",
          "destination_type": "queue",
          "routing_key": "",
          "arguments": {
          }
        }
      ]
    }