global:
  environment: "production"
  dockerRegistryRepository:
  defaultStorageClassName: standard
  mysqlReadyImage:
    name: mysql/mysql-server
    tag: 8.0.14
  postgresReadyImage:
    name: jbergknoff/postgresql-client
    tag: latest
  imagePullPolicy: IfNotPresent
  userService:
    route: /api/users
  keycloak:
    route: /auth
  guildService:
    route: /api/guilds
  channelService:
    route: /api/channels
  rabbitmq:
    env: .env.prod
  FAASUrl:
    BadWords: https://dappfunctions.azurewebsites.net/api/filterwords
  RootUrl: http://34.89.147.199