global:
  environment: "production"
  dockerRegistryRepository:
  defaultStorageClassName: default
  mysqlReadyImage:
    name: mysql/mysql-server
    tag: 8.0.14
  postgresReadyImage:
    name: jbergknoff/postgresql-client
    tag: latest
  imagePullPolicy: IfNotPresent
  userService:
    route: /api/users
  keycloak:
    route: /auth
  commandService:
    route: /api/command
  villageService:
    route: /api/village
  rabbitmq:
    env: .env.prod
  FAASUrl:
    BadWords: https://dappfunctions.azurewebsites.net/api/filterwords
  RootUrl: http://s6mgame-dns-4d95ae3e.hcp.westeurope.azmk8s.io
  authkey: 3fa85f64-5717-4562-b3fc-2c963f66afa0