global:
  environment: "development"
  dockerRegistryRepository:
  defaultStorageClassName: standard
  mysqlReadyImage:
    name: mysql/mysql-server
    tag: 8.0.14
  postgresReadyImage:
    name: jbergknoff/postgresql-client
    tag: latest
  imagePullPolicy: Never
  userService:
    route: /api/users
  keycloak:
    route: /auth
  commandService:
    route: /api/command
  villageService:
    route: village-service
  rabbitmq:
    env: .env.dev
  FAASUrl:
    BadWords: https://dappfunctions.azurewebsites.net/api/filterwords
  RootUrl: 
  authkey: 3fa85f64-5717-4562-b3fc-2c963f66afa0