apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-http
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: {{.Values.global.keycloak.route}}/$2
spec:
  rules:
  - http:
      paths:
      - path: {{.Values.global.keycloak.route}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-http
            port:
              number: {{ .Values.keycloak.service.httpPort }}